# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-08-16 03:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmember',
            name='permission',
            field=models.IntegerField(choices=[(1, 'Admin'), (2, 'Project Manager'), (3, 'Developer'), (4, 'Viewer')], default=1),
        ),
        migrations.AlterField(
            model_name='tasklog',
            name='start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
