# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-18 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetracker', '0005_auto_20160817_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='order',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
